//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBO.OrderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderService.orderServiceSoap")]
    public interface orderServiceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  deviceID 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeviceTime", ReplyAction="*")]
        WebBO.OrderService.getDeviceTimeResponse getDeviceTime(WebBO.OrderService.getDeviceTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeviceTime", ReplyAction="*")]
        System.Threading.Tasks.Task<WebBO.OrderService.getDeviceTimeResponse> getDeviceTimeAsync(WebBO.OrderService.getDeviceTimeRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  deviceID 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeviceTimeByAddr", ReplyAction="*")]
        WebBO.OrderService.getDeviceTimeByAddrResponse getDeviceTimeByAddr(WebBO.OrderService.getDeviceTimeByAddrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeviceTimeByAddr", ReplyAction="*")]
        System.Threading.Tasks.Task<WebBO.OrderService.getDeviceTimeByAddrResponse> getDeviceTimeByAddrAsync(WebBO.OrderService.getDeviceTimeByAddrRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  deviceID 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWDData", ReplyAction="*")]
        WebBO.OrderService.getWDDataResponse getWDData(WebBO.OrderService.getWDDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWDData", ReplyAction="*")]
        System.Threading.Tasks.Task<WebBO.OrderService.getWDDataResponse> getWDDataAsync(WebBO.OrderService.getWDDataRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  deviceID 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWDDataByAddr", ReplyAction="*")]
        WebBO.OrderService.getWDDataByAddrResponse getWDDataByAddr(WebBO.OrderService.getWDDataByAddrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWDDataByAddr", ReplyAction="*")]
        System.Threading.Tasks.Task<WebBO.OrderService.getWDDataByAddrResponse> getWDDataByAddrAsync(WebBO.OrderService.getWDDataByAddrRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  deviceID 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRDData", ReplyAction="*")]
        WebBO.OrderService.getRDDataResponse getRDData(WebBO.OrderService.getRDDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRDData", ReplyAction="*")]
        System.Threading.Tasks.Task<WebBO.OrderService.getRDDataResponse> getRDDataAsync(WebBO.OrderService.getRDDataRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  deviceID 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRDDataByAddr", ReplyAction="*")]
        WebBO.OrderService.getRDDataByAddrResponse getRDDataByAddr(WebBO.OrderService.getRDDataByAddrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRDDataByAddr", ReplyAction="*")]
        System.Threading.Tasks.Task<WebBO.OrderService.getRDDataByAddrResponse> getRDDataByAddrAsync(WebBO.OrderService.getRDDataByAddrRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  deviceID 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setDeviceTime", ReplyAction="*")]
        WebBO.OrderService.setDeviceTimeResponse setDeviceTime(WebBO.OrderService.setDeviceTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setDeviceTime", ReplyAction="*")]
        System.Threading.Tasks.Task<WebBO.OrderService.setDeviceTimeResponse> setDeviceTimeAsync(WebBO.OrderService.setDeviceTimeRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  deviceID 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setDeviceTimeByAddr", ReplyAction="*")]
        WebBO.OrderService.setDeviceTimeByAddrResponse setDeviceTimeByAddr(WebBO.OrderService.setDeviceTimeByAddrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setDeviceTimeByAddr", ReplyAction="*")]
        System.Threading.Tasks.Task<WebBO.OrderService.setDeviceTimeByAddrResponse> setDeviceTimeByAddrAsync(WebBO.OrderService.setDeviceTimeByAddrRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDeviceTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDeviceTime", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.getDeviceTimeRequestBody Body;
        
        public getDeviceTimeRequest() {
        }
        
        public getDeviceTimeRequest(WebBO.OrderService.getDeviceTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDeviceTimeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deviceID;
        
        public getDeviceTimeRequestBody() {
        }
        
        public getDeviceTimeRequestBody(string deviceID) {
            this.deviceID = deviceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDeviceTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDeviceTimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.getDeviceTimeResponseBody Body;
        
        public getDeviceTimeResponse() {
        }
        
        public getDeviceTimeResponse(WebBO.OrderService.getDeviceTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDeviceTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDeviceTimeResult;
        
        public getDeviceTimeResponseBody() {
        }
        
        public getDeviceTimeResponseBody(string getDeviceTimeResult) {
            this.getDeviceTimeResult = getDeviceTimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDeviceTimeByAddrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDeviceTimeByAddr", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.getDeviceTimeByAddrRequestBody Body;
        
        public getDeviceTimeByAddrRequest() {
        }
        
        public getDeviceTimeByAddrRequest(WebBO.OrderService.getDeviceTimeByAddrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDeviceTimeByAddrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deviceID;
        
        public getDeviceTimeByAddrRequestBody() {
        }
        
        public getDeviceTimeByAddrRequestBody(string deviceID) {
            this.deviceID = deviceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDeviceTimeByAddrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDeviceTimeByAddrResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.getDeviceTimeByAddrResponseBody Body;
        
        public getDeviceTimeByAddrResponse() {
        }
        
        public getDeviceTimeByAddrResponse(WebBO.OrderService.getDeviceTimeByAddrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDeviceTimeByAddrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDeviceTimeByAddrResult;
        
        public getDeviceTimeByAddrResponseBody() {
        }
        
        public getDeviceTimeByAddrResponseBody(string getDeviceTimeByAddrResult) {
            this.getDeviceTimeByAddrResult = getDeviceTimeByAddrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWDDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWDData", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.getWDDataRequestBody Body;
        
        public getWDDataRequest() {
        }
        
        public getWDDataRequest(WebBO.OrderService.getWDDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWDDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deviceID;
        
        public getWDDataRequestBody() {
        }
        
        public getWDDataRequestBody(string deviceID) {
            this.deviceID = deviceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWDDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWDDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.getWDDataResponseBody Body;
        
        public getWDDataResponse() {
        }
        
        public getWDDataResponse(WebBO.OrderService.getWDDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWDDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getWDDataResult;
        
        public getWDDataResponseBody() {
        }
        
        public getWDDataResponseBody(string getWDDataResult) {
            this.getWDDataResult = getWDDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWDDataByAddrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWDDataByAddr", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.getWDDataByAddrRequestBody Body;
        
        public getWDDataByAddrRequest() {
        }
        
        public getWDDataByAddrRequest(WebBO.OrderService.getWDDataByAddrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWDDataByAddrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deviceID;
        
        public getWDDataByAddrRequestBody() {
        }
        
        public getWDDataByAddrRequestBody(string deviceID) {
            this.deviceID = deviceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWDDataByAddrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWDDataByAddrResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.getWDDataByAddrResponseBody Body;
        
        public getWDDataByAddrResponse() {
        }
        
        public getWDDataByAddrResponse(WebBO.OrderService.getWDDataByAddrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWDDataByAddrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getWDDataByAddrResult;
        
        public getWDDataByAddrResponseBody() {
        }
        
        public getWDDataByAddrResponseBody(string getWDDataByAddrResult) {
            this.getWDDataByAddrResult = getWDDataByAddrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRDDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRDData", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.getRDDataRequestBody Body;
        
        public getRDDataRequest() {
        }
        
        public getRDDataRequest(WebBO.OrderService.getRDDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRDDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deviceID;
        
        public getRDDataRequestBody() {
        }
        
        public getRDDataRequestBody(string deviceID) {
            this.deviceID = deviceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRDDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRDDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.getRDDataResponseBody Body;
        
        public getRDDataResponse() {
        }
        
        public getRDDataResponse(WebBO.OrderService.getRDDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRDDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRDDataResult;
        
        public getRDDataResponseBody() {
        }
        
        public getRDDataResponseBody(string getRDDataResult) {
            this.getRDDataResult = getRDDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRDDataByAddrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRDDataByAddr", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.getRDDataByAddrRequestBody Body;
        
        public getRDDataByAddrRequest() {
        }
        
        public getRDDataByAddrRequest(WebBO.OrderService.getRDDataByAddrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRDDataByAddrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deviceID;
        
        public getRDDataByAddrRequestBody() {
        }
        
        public getRDDataByAddrRequestBody(string deviceID) {
            this.deviceID = deviceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRDDataByAddrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRDDataByAddrResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.getRDDataByAddrResponseBody Body;
        
        public getRDDataByAddrResponse() {
        }
        
        public getRDDataByAddrResponse(WebBO.OrderService.getRDDataByAddrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRDDataByAddrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRDDataByAddrResult;
        
        public getRDDataByAddrResponseBody() {
        }
        
        public getRDDataByAddrResponseBody(string getRDDataByAddrResult) {
            this.getRDDataByAddrResult = getRDDataByAddrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeviceTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeviceTime", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.setDeviceTimeRequestBody Body;
        
        public setDeviceTimeRequest() {
        }
        
        public setDeviceTimeRequest(WebBO.OrderService.setDeviceTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setDeviceTimeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deviceID;
        
        public setDeviceTimeRequestBody() {
        }
        
        public setDeviceTimeRequestBody(string deviceID) {
            this.deviceID = deviceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeviceTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeviceTimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.setDeviceTimeResponseBody Body;
        
        public setDeviceTimeResponse() {
        }
        
        public setDeviceTimeResponse(WebBO.OrderService.setDeviceTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setDeviceTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setDeviceTimeResult;
        
        public setDeviceTimeResponseBody() {
        }
        
        public setDeviceTimeResponseBody(string setDeviceTimeResult) {
            this.setDeviceTimeResult = setDeviceTimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeviceTimeByAddrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeviceTimeByAddr", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.setDeviceTimeByAddrRequestBody Body;
        
        public setDeviceTimeByAddrRequest() {
        }
        
        public setDeviceTimeByAddrRequest(WebBO.OrderService.setDeviceTimeByAddrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setDeviceTimeByAddrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deviceID;
        
        public setDeviceTimeByAddrRequestBody() {
        }
        
        public setDeviceTimeByAddrRequestBody(string deviceID) {
            this.deviceID = deviceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeviceTimeByAddrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeviceTimeByAddrResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBO.OrderService.setDeviceTimeByAddrResponseBody Body;
        
        public setDeviceTimeByAddrResponse() {
        }
        
        public setDeviceTimeByAddrResponse(WebBO.OrderService.setDeviceTimeByAddrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setDeviceTimeByAddrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setDeviceTimeByAddrResult;
        
        public setDeviceTimeByAddrResponseBody() {
        }
        
        public setDeviceTimeByAddrResponseBody(string setDeviceTimeByAddrResult) {
            this.setDeviceTimeByAddrResult = setDeviceTimeByAddrResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface orderServiceSoapChannel : WebBO.OrderService.orderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class orderServiceSoapClient : System.ServiceModel.ClientBase<WebBO.OrderService.orderServiceSoap>, WebBO.OrderService.orderServiceSoap {
        
        public orderServiceSoapClient() {
        }
        
        public orderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public orderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public orderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public orderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBO.OrderService.getDeviceTimeResponse WebBO.OrderService.orderServiceSoap.getDeviceTime(WebBO.OrderService.getDeviceTimeRequest request) {
            return base.Channel.getDeviceTime(request);
        }
        
        public string getDeviceTime(string deviceID) {
            WebBO.OrderService.getDeviceTimeRequest inValue = new WebBO.OrderService.getDeviceTimeRequest();
            inValue.Body = new WebBO.OrderService.getDeviceTimeRequestBody();
            inValue.Body.deviceID = deviceID;
            WebBO.OrderService.getDeviceTimeResponse retVal = ((WebBO.OrderService.orderServiceSoap)(this)).getDeviceTime(inValue);
            return retVal.Body.getDeviceTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBO.OrderService.getDeviceTimeResponse> WebBO.OrderService.orderServiceSoap.getDeviceTimeAsync(WebBO.OrderService.getDeviceTimeRequest request) {
            return base.Channel.getDeviceTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBO.OrderService.getDeviceTimeResponse> getDeviceTimeAsync(string deviceID) {
            WebBO.OrderService.getDeviceTimeRequest inValue = new WebBO.OrderService.getDeviceTimeRequest();
            inValue.Body = new WebBO.OrderService.getDeviceTimeRequestBody();
            inValue.Body.deviceID = deviceID;
            return ((WebBO.OrderService.orderServiceSoap)(this)).getDeviceTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBO.OrderService.getDeviceTimeByAddrResponse WebBO.OrderService.orderServiceSoap.getDeviceTimeByAddr(WebBO.OrderService.getDeviceTimeByAddrRequest request) {
            return base.Channel.getDeviceTimeByAddr(request);
        }
        
        public string getDeviceTimeByAddr(string deviceID) {
            WebBO.OrderService.getDeviceTimeByAddrRequest inValue = new WebBO.OrderService.getDeviceTimeByAddrRequest();
            inValue.Body = new WebBO.OrderService.getDeviceTimeByAddrRequestBody();
            inValue.Body.deviceID = deviceID;
            WebBO.OrderService.getDeviceTimeByAddrResponse retVal = ((WebBO.OrderService.orderServiceSoap)(this)).getDeviceTimeByAddr(inValue);
            return retVal.Body.getDeviceTimeByAddrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBO.OrderService.getDeviceTimeByAddrResponse> WebBO.OrderService.orderServiceSoap.getDeviceTimeByAddrAsync(WebBO.OrderService.getDeviceTimeByAddrRequest request) {
            return base.Channel.getDeviceTimeByAddrAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBO.OrderService.getDeviceTimeByAddrResponse> getDeviceTimeByAddrAsync(string deviceID) {
            WebBO.OrderService.getDeviceTimeByAddrRequest inValue = new WebBO.OrderService.getDeviceTimeByAddrRequest();
            inValue.Body = new WebBO.OrderService.getDeviceTimeByAddrRequestBody();
            inValue.Body.deviceID = deviceID;
            return ((WebBO.OrderService.orderServiceSoap)(this)).getDeviceTimeByAddrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBO.OrderService.getWDDataResponse WebBO.OrderService.orderServiceSoap.getWDData(WebBO.OrderService.getWDDataRequest request) {
            return base.Channel.getWDData(request);
        }
        
        public string getWDData(string deviceID) {
            WebBO.OrderService.getWDDataRequest inValue = new WebBO.OrderService.getWDDataRequest();
            inValue.Body = new WebBO.OrderService.getWDDataRequestBody();
            inValue.Body.deviceID = deviceID;
            WebBO.OrderService.getWDDataResponse retVal = ((WebBO.OrderService.orderServiceSoap)(this)).getWDData(inValue);
            return retVal.Body.getWDDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBO.OrderService.getWDDataResponse> WebBO.OrderService.orderServiceSoap.getWDDataAsync(WebBO.OrderService.getWDDataRequest request) {
            return base.Channel.getWDDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBO.OrderService.getWDDataResponse> getWDDataAsync(string deviceID) {
            WebBO.OrderService.getWDDataRequest inValue = new WebBO.OrderService.getWDDataRequest();
            inValue.Body = new WebBO.OrderService.getWDDataRequestBody();
            inValue.Body.deviceID = deviceID;
            return ((WebBO.OrderService.orderServiceSoap)(this)).getWDDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBO.OrderService.getWDDataByAddrResponse WebBO.OrderService.orderServiceSoap.getWDDataByAddr(WebBO.OrderService.getWDDataByAddrRequest request) {
            return base.Channel.getWDDataByAddr(request);
        }
        
        public string getWDDataByAddr(string deviceID) {
            WebBO.OrderService.getWDDataByAddrRequest inValue = new WebBO.OrderService.getWDDataByAddrRequest();
            inValue.Body = new WebBO.OrderService.getWDDataByAddrRequestBody();
            inValue.Body.deviceID = deviceID;
            WebBO.OrderService.getWDDataByAddrResponse retVal = ((WebBO.OrderService.orderServiceSoap)(this)).getWDDataByAddr(inValue);
            return retVal.Body.getWDDataByAddrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBO.OrderService.getWDDataByAddrResponse> WebBO.OrderService.orderServiceSoap.getWDDataByAddrAsync(WebBO.OrderService.getWDDataByAddrRequest request) {
            return base.Channel.getWDDataByAddrAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBO.OrderService.getWDDataByAddrResponse> getWDDataByAddrAsync(string deviceID) {
            WebBO.OrderService.getWDDataByAddrRequest inValue = new WebBO.OrderService.getWDDataByAddrRequest();
            inValue.Body = new WebBO.OrderService.getWDDataByAddrRequestBody();
            inValue.Body.deviceID = deviceID;
            return ((WebBO.OrderService.orderServiceSoap)(this)).getWDDataByAddrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBO.OrderService.getRDDataResponse WebBO.OrderService.orderServiceSoap.getRDData(WebBO.OrderService.getRDDataRequest request) {
            return base.Channel.getRDData(request);
        }
        
        public string getRDData(string deviceID) {
            WebBO.OrderService.getRDDataRequest inValue = new WebBO.OrderService.getRDDataRequest();
            inValue.Body = new WebBO.OrderService.getRDDataRequestBody();
            inValue.Body.deviceID = deviceID;
            WebBO.OrderService.getRDDataResponse retVal = ((WebBO.OrderService.orderServiceSoap)(this)).getRDData(inValue);
            return retVal.Body.getRDDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBO.OrderService.getRDDataResponse> WebBO.OrderService.orderServiceSoap.getRDDataAsync(WebBO.OrderService.getRDDataRequest request) {
            return base.Channel.getRDDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBO.OrderService.getRDDataResponse> getRDDataAsync(string deviceID) {
            WebBO.OrderService.getRDDataRequest inValue = new WebBO.OrderService.getRDDataRequest();
            inValue.Body = new WebBO.OrderService.getRDDataRequestBody();
            inValue.Body.deviceID = deviceID;
            return ((WebBO.OrderService.orderServiceSoap)(this)).getRDDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBO.OrderService.getRDDataByAddrResponse WebBO.OrderService.orderServiceSoap.getRDDataByAddr(WebBO.OrderService.getRDDataByAddrRequest request) {
            return base.Channel.getRDDataByAddr(request);
        }
        
        public string getRDDataByAddr(string deviceID) {
            WebBO.OrderService.getRDDataByAddrRequest inValue = new WebBO.OrderService.getRDDataByAddrRequest();
            inValue.Body = new WebBO.OrderService.getRDDataByAddrRequestBody();
            inValue.Body.deviceID = deviceID;
            WebBO.OrderService.getRDDataByAddrResponse retVal = ((WebBO.OrderService.orderServiceSoap)(this)).getRDDataByAddr(inValue);
            return retVal.Body.getRDDataByAddrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBO.OrderService.getRDDataByAddrResponse> WebBO.OrderService.orderServiceSoap.getRDDataByAddrAsync(WebBO.OrderService.getRDDataByAddrRequest request) {
            return base.Channel.getRDDataByAddrAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBO.OrderService.getRDDataByAddrResponse> getRDDataByAddrAsync(string deviceID) {
            WebBO.OrderService.getRDDataByAddrRequest inValue = new WebBO.OrderService.getRDDataByAddrRequest();
            inValue.Body = new WebBO.OrderService.getRDDataByAddrRequestBody();
            inValue.Body.deviceID = deviceID;
            return ((WebBO.OrderService.orderServiceSoap)(this)).getRDDataByAddrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBO.OrderService.setDeviceTimeResponse WebBO.OrderService.orderServiceSoap.setDeviceTime(WebBO.OrderService.setDeviceTimeRequest request) {
            return base.Channel.setDeviceTime(request);
        }
        
        public string setDeviceTime(string deviceID) {
            WebBO.OrderService.setDeviceTimeRequest inValue = new WebBO.OrderService.setDeviceTimeRequest();
            inValue.Body = new WebBO.OrderService.setDeviceTimeRequestBody();
            inValue.Body.deviceID = deviceID;
            WebBO.OrderService.setDeviceTimeResponse retVal = ((WebBO.OrderService.orderServiceSoap)(this)).setDeviceTime(inValue);
            return retVal.Body.setDeviceTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBO.OrderService.setDeviceTimeResponse> WebBO.OrderService.orderServiceSoap.setDeviceTimeAsync(WebBO.OrderService.setDeviceTimeRequest request) {
            return base.Channel.setDeviceTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBO.OrderService.setDeviceTimeResponse> setDeviceTimeAsync(string deviceID) {
            WebBO.OrderService.setDeviceTimeRequest inValue = new WebBO.OrderService.setDeviceTimeRequest();
            inValue.Body = new WebBO.OrderService.setDeviceTimeRequestBody();
            inValue.Body.deviceID = deviceID;
            return ((WebBO.OrderService.orderServiceSoap)(this)).setDeviceTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBO.OrderService.setDeviceTimeByAddrResponse WebBO.OrderService.orderServiceSoap.setDeviceTimeByAddr(WebBO.OrderService.setDeviceTimeByAddrRequest request) {
            return base.Channel.setDeviceTimeByAddr(request);
        }
        
        public string setDeviceTimeByAddr(string deviceID) {
            WebBO.OrderService.setDeviceTimeByAddrRequest inValue = new WebBO.OrderService.setDeviceTimeByAddrRequest();
            inValue.Body = new WebBO.OrderService.setDeviceTimeByAddrRequestBody();
            inValue.Body.deviceID = deviceID;
            WebBO.OrderService.setDeviceTimeByAddrResponse retVal = ((WebBO.OrderService.orderServiceSoap)(this)).setDeviceTimeByAddr(inValue);
            return retVal.Body.setDeviceTimeByAddrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebBO.OrderService.setDeviceTimeByAddrResponse> WebBO.OrderService.orderServiceSoap.setDeviceTimeByAddrAsync(WebBO.OrderService.setDeviceTimeByAddrRequest request) {
            return base.Channel.setDeviceTimeByAddrAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebBO.OrderService.setDeviceTimeByAddrResponse> setDeviceTimeByAddrAsync(string deviceID) {
            WebBO.OrderService.setDeviceTimeByAddrRequest inValue = new WebBO.OrderService.setDeviceTimeByAddrRequest();
            inValue.Body = new WebBO.OrderService.setDeviceTimeByAddrRequestBody();
            inValue.Body.deviceID = deviceID;
            return ((WebBO.OrderService.orderServiceSoap)(this)).setDeviceTimeByAddrAsync(inValue);
        }
    }
}
