//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAppSurveyTable
    {
        public string AppSurveyTableID { get; set; }
        public string AppSurveyID { get; set; }
        public string TableAlias { get; set; }
        public string TableName { get; set; }
        public string ForeignKey { get; set; }
        public bool IsMustHave { get; set; }
    }
}
