//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAppSurvey
    {
        public string AppSurveyID { get; set; }
        public string AppSurveyNo { get; set; }
        public Nullable<System.DateTime> AppSurveyStartDate { get; set; }
        public Nullable<System.DateTime> AppSurveyEndDate { get; set; }
        public string AppSurveyPurpose { get; set; }
        public string AppSurveyStatus { get; set; }
        public string AppSurveyStateName { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
