//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAppContractTypeDoc
    {
        public string AppContractTypeDocID { get; set; }
        public string AppContractType { get; set; }
        public string DocumentName { get; set; }
        public string DocumentDesc { get; set; }
        public string MustHaveType { get; set; }
        public Nullable<int> CopiesNumber { get; set; }
        public string DispType { get; set; }
        public Nullable<int> OrderKey { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public string DocumentData { get; set; }
    }
}
