//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbContractFruit
    {
        public string ContractFruitID { get; set; }
        public string ContractID { get; set; }
        public string TreeTableName { get; set; }
        public string TreeTableKey { get; set; }
        public string TreeFruitID { get; set; }
        public string AppSurveyID { get; set; }
        public string AppSurveyPlantTreeID { get; set; }
        public string AppSurveyStatus { get; set; }
        public string TreeID { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<System.DateTime> PlantDate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> CollectTenor { get; set; }
        public Nullable<decimal> TransferTenor { get; set; }
        public string Memo { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
