//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNSAllotReceive
    {
        public string NSAllotReceiveID { get; set; }
        public string NSAllotID { get; set; }
        public string NSAllotDetailID { get; set; }
        public string NSCultivateTreeID { get; set; }
        public int ReceiveQuantity { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public string SeedlingHigh { get; set; }
        public double SeedlingDiameter { get; set; }
        public bool IsLock { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
