//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNSCultivateWorkItemTemplate
    {
        public string NSCultivateWorkItemTemplateID { get; set; }
        public string NSScheduleTemplateID { get; set; }
        public string Category { get; set; }
        public string WorkItemName { get; set; }
        public string RecordItemName { get; set; }
        public bool IsPurchase { get; set; }
        public int OrderKey { get; set; }
        public double Total { get; set; }
        public string Unit { get; set; }
        public string Fee { get; set; }
        public string ModifyUser { get; set; }
        public System.DateTime ModifyDate { get; set; }
    }
}
