//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRTLandValueTemp
    {
        public string RTLandValueSurveyID { get; set; }
        public string RTLandExtendID { get; set; }
        public int LevyYear { get; set; }
        public int RentYear { get; set; }
        public string UNIT { get; set; }
        public string SEC { get; set; }
        public string NO { get; set; }
        public string PriceYear { get; set; }
        public Nullable<decimal> LandPrice { get; set; }
        public Nullable<decimal> CurrentValue { get; set; }
        public Nullable<decimal> AppraisalLandValue { get; set; }
        public string ResponseResult { get; set; }
        public string ResultExplain { get; set; }
        public System.DateTime ResponseDate { get; set; }
    }
}
