//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSysUserData
    {
        public string UserID { get; set; }
        public string Password { get; set; }
        public string SysOrganizationID { get; set; }
        public string SysGroupID { get; set; }
        public string UserName { get; set; }
        public string SubOrganizationName { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsDirector { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string CellPhone { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> LastResetPwTime { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string IsDel { get; set; }
    }
}
