//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTMLandListResurvey
    {
        public string TMLandListResurveyID { get; set; }
        public int TMLandListID { get; set; }
        public string MyKey { get; set; }
        public string CityCode { get; set; }
        public string City { get; set; }
        public string CityAreaCode { get; set; }
        public string CityArea { get; set; }
        public string DistrictCode { get; set; }
        public string District { get; set; }
        public string LandNumber { get; set; }
        public string ModifyUser { get; set; }
        public System.DateTime ModifyDate { get; set; }
    }
}
