//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTMLandList
    {
        public int Id { get; set; }
        public string Guid { get; set; }
        public string MyKey { get; set; }
        public string UnifiedNo { get; set; }
        public string Name { get; set; }
        public string CityCode { get; set; }
        public string City { get; set; }
        public string CityAreaCode { get; set; }
        public string CityArea { get; set; }
        public string DistrictCode { get; set; }
        public string District { get; set; }
        public string LandNumber { get; set; }
        public Nullable<decimal> SurfaceArea { get; set; }
        public string RegistrationOrder { get; set; }
        public string Owner { get; set; }
        public string RightRegion { get; set; }
        public string LandUseZoning { get; set; }
        public string LandUseClassification { get; set; }
        public string CurrentLandValue { get; set; }
        public string DeclaredLandValueDate { get; set; }
        public string DeclaredLandValue { get; set; }
        public string SerialNumber { get; set; }
        public string PropertyName { get; set; }
        public string CertificateNo { get; set; }
        public string Workstation { get; set; }
        public string Department { get; set; }
        public string ModalityIn { get; set; }
        public string StatusIn { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Transfer { get; set; }
        public string Modality { get; set; }
        public string Status { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public bool IsDelete { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateStatus { get; set; }
    }
}
