//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ContractLand
    {
        public string ContractLandID { get; set; }
        public string ContractID { get; set; }
        public string LandName { get; set; }
        public string UsePurpose { get; set; }
        public string ZoneNo { get; set; }
        public string InOutWorkAreaName { get; set; }
        public string Memo { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string ContractLandForestID { get; set; }
        public string WorkAreaID { get; set; }
        public string WorkAreaName { get; set; }
        public string SegMentLandNo { get; set; }
        public string PrivateLandNo { get; set; }
        public string ContractLandCadastralID { get; set; }
        public string LandCadastralID { get; set; }
        public Nullable<bool> IsAllRent { get; set; }
        public string CityID { get; set; }
        public string CityName { get; set; }
        public string TownID { get; set; }
        public string TownName { get; set; }
        public string MainSec { get; set; }
        public string SubSec { get; set; }
        public string LandNo { get; set; }
        public string CadPrivateLandNo { get; set; }
        public Nullable<decimal> CadArea { get; set; }
        public string FullLandCadastralName { get; set; }
        public string SimpLandCadastralName { get; set; }
        public string FullLandForestName { get; set; }
        public string SimpLandForestName { get; set; }
    }
}
