//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ContractAccept
    {
        public string ContractID { get; set; }
        public string ContractStatusID { get; set; }
        public string LandContractID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ExpirtyDate { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string RentCode { get; set; }
        public string ContractClassify { get; set; }
        public Nullable<System.DateTime> ContractChangeDate { get; set; }
        public string ContractChangeNo { get; set; }
        public string ContractChangePurpose { get; set; }
        public Nullable<int> AgreeOrder { get; set; }
        public string UsePurpose { get; set; }
        public string LandKindName { get; set; }
        public string WorkStationID { get; set; }
        public string Memo { get; set; }
        public string SourceContractID { get; set; }
        public string LesseeName { get; set; }
        public string AppFormID { get; set; }
        public string AppContractStatus { get; set; }
        public string AppFormStatus { get; set; }
        public string IsAppFormDataOK { get; set; }
        public string AppTypeName { get; set; }
        public string AppTypeState { get; set; }
        public string AppTypeStateID { get; set; }
        public string AppContractTypeID { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public string AcceptUser { get; set; }
        public string UnderTaker { get; set; }
    }
}
