//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RTUpdateLandPrice
    {
        public string ContractID { get; set; }
        public string LandContractID { get; set; }
        public string RTLandExtendID { get; set; }
        public string ContractLandCadastralID { get; set; }
        public string WorkStationID { get; set; }
        public string RentCalcType { get; set; }
        public string CityID { get; set; }
        public string TownID { get; set; }
        public string MainSec { get; set; }
        public string SubSec { get; set; }
        public string LandNo { get; set; }
        public string Unit { get; set; }
        public string SecCode { get; set; }
        public Nullable<int> LevyYear { get; set; }
        public Nullable<int> RentYear { get; set; }
        public string PriceYear { get; set; }
        public Nullable<decimal> LandPrice { get; set; }
        public Nullable<decimal> CurrentValue { get; set; }
        public Nullable<decimal> AppraisalLandValue { get; set; }
        public string ResponseResult { get; set; }
        public string ResultExplain { get; set; }
        public string RTLandValueSurveyID { get; set; }
    }
}
