//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.17929
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic_hm.LDAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LDAP.statusAcPwValidateSoap")]
    public interface statusAcPwValidateSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetValidateCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetValidateCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/encodeMD5", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string encodeMD5(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AcPwValidate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AcPwValidate(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmloy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Traffic_hm.LDAP.emloy GetEmloy(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Traffic_hm.LDAP.Newmail GetMessage(string Emp_Id, string Sender, string Subject, string Body, string Urlfiles);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class emloy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string employ_noField;
        
        private string department_idField;
        
        private string department_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string employ_no {
            get {
                return this.employ_noField;
            }
            set {
                this.employ_noField = value;
                this.RaisePropertyChanged("employ_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string department_id {
            get {
                return this.department_idField;
            }
            set {
                this.department_idField = value;
                this.RaisePropertyChanged("department_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string department_name {
            get {
                return this.department_nameField;
            }
            set {
                this.department_nameField = value;
                this.RaisePropertyChanged("department_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Newmail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private bool resultField;
        
        private string strResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string strResult {
            get {
                return this.strResultField;
            }
            set {
                this.strResultField = value;
                this.RaisePropertyChanged("strResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface statusAcPwValidateSoapChannel : Traffic_hm.LDAP.statusAcPwValidateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class statusAcPwValidateSoapClient : System.ServiceModel.ClientBase<Traffic_hm.LDAP.statusAcPwValidateSoap>, Traffic_hm.LDAP.statusAcPwValidateSoap {
        
        public statusAcPwValidateSoapClient() {
        }
        
        public statusAcPwValidateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public statusAcPwValidateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public statusAcPwValidateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public statusAcPwValidateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetValidateCode() {
            return base.Channel.GetValidateCode();
        }
        
        public string encodeMD5(string input) {
            return base.Channel.encodeMD5(input);
        }
        
        public string AcPwValidate(string input) {
            return base.Channel.AcPwValidate(input);
        }
        
        public Traffic_hm.LDAP.emloy GetEmloy(string input) {
            return base.Channel.GetEmloy(input);
        }
        
        public Traffic_hm.LDAP.Newmail GetMessage(string Emp_Id, string Sender, string Subject, string Body, string Urlfiles) {
            return base.Channel.GetMessage(Emp_Id, Sender, Subject, Body, Urlfiles);
        }
    }
}
